Inital Commit Ganesh for Create job Page
ZenEducation/ZenVerse pull request #1
Opened 2023-02-25 04:56 UTC by gmganesh3110

2023-02-27 17:44 UTC, panthsolanki requested changes

2023-02-27 17:44 UTC, panthsolanki commented on layouts/default.vue
> +      <!-- <slot /> -->
don't add form here, create page under career folder

2023-02-27 17:44 UTC, panthsolanki commented on pages/careers/CreateJob.vue
> +        <button
use BaseButtons component

2023-02-27 17:44 UTC, panthsolanki commented on layouts/default.vue
> -</template>
dont make any change in this file

2023-02-27 17:44 UTC, panthsolanki commented on components/Forms/CreateJob.vue
> +                type="checkbox"
checkbox should be in one single group, pls update the logic

2023-02-27 17:44 UTC, panthsolanki commented on components/Forms/CreateJob.vue
> +          <div class="checkboxes">
checkbox should also be in single group

2023-02-27 18:19 UTC, gmganesh3110 commented on layouts/default.vue
> +      <!-- <slot /> -->
Removed SIr

2023-02-27 18:19 UTC, gmganesh3110 commented on pages/careers/CreateJob.vue
> +        <button
Used Base Buttons and Updated sir

2023-02-28 16:52 UTC, panthsolanki submitted a review, later dismissed

2023-03-17 04:16 UTC, panthsolanki approved these changes

2023-03-18 04:00 UTC, merged